/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.helper.ShareHelper;
import com.edusys.helper.XImage;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Timer;

/**
 *
 * @author Dell
 */
public class EduSysJFrame extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form EduSysJFrame
     */
    public EduSysJFrame() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jToolBar1 = new javax.swing.JToolBar();
        btn_dangXuat = new javax.swing.JButton();
        btn_ketThuc = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btn_chuyenDe = new javax.swing.JButton();
        btn_nguoiHoc = new javax.swing.JButton();
        btn_khoaHoc = new javax.swing.JButton();
        btn_hocVien = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btn_huongDan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_trangThai = new javax.swing.JLabel();
        lbl_dongHo = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mni_dangNhap = new javax.swing.JMenuItem();
        mni_dangXuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mni_doiMatKhau = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mni_ketThuc = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mni_chuyenDe = new javax.swing.JMenuItem();
        mni_khoaHoc = new javax.swing.JMenuItem();
        mni_nguoiHoc = new javax.swing.JMenuItem();
        mni_hocVien = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mni_nhanVien = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mni_thongKeNguoiHoc = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mni_thongKeBangDiem = new javax.swing.JMenuItem();
        mni_thongKeKhoaHoc = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mni_thongKeDoanhThu = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mni_huongDan = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mni_gioiThieu = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setRollover(true);

        btn_dangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Exit.png"))); // NOI18N
        btn_dangXuat.setText("Đăng xuất");
        btn_dangXuat.setFocusable(false);
        btn_dangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_dangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_dangXuat);

        btn_ketThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Stop.png"))); // NOI18N
        btn_ketThuc.setText("Kết thúc");
        btn_ketThuc.setFocusable(false);
        btn_ketThuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ketThuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_ketThuc);
        jToolBar1.add(jSeparator7);

        btn_chuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Lists.png"))); // NOI18N
        btn_chuyenDe.setText("Chuyên đề");
        btn_chuyenDe.setFocusable(false);
        btn_chuyenDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_chuyenDe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_chuyenDe);

        btn_nguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Conference.png"))); // NOI18N
        btn_nguoiHoc.setText("Người học");
        btn_nguoiHoc.setFocusable(false);
        btn_nguoiHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nguoiHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_nguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nguoiHocActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_nguoiHoc);

        btn_khoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Certificate.png"))); // NOI18N
        btn_khoaHoc.setText("Khóa học");
        btn_khoaHoc.setFocusable(false);
        btn_khoaHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_khoaHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_khoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_khoaHocActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_khoaHoc);

        btn_hocVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/User.png"))); // NOI18N
        btn_hocVien.setText("Học viên");
        btn_hocVien.setFocusable(false);
        btn_hocVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_hocVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_hocVien);
        jToolBar1.add(jSeparator8);

        btn_huongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Globe.png"))); // NOI18N
        btn_huongDan.setText("Hướng dẫn");
        btn_huongDan.setFocusable(false);
        btn_huongDan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_huongDan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_huongDan);

        lbl_trangThai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Info.png"))); // NOI18N
        lbl_trangThai.setText("Hệ quản lý đào tạo");

        lbl_dongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Alarm.png"))); // NOI18N
        lbl_dongHo.setText("00:00:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_trangThai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_dongHo))
            .addComponent(jSeparator9)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_trangThai)
                    .addComponent(lbl_dongHo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/ongVang2.png"))); // NOI18N
        jLabel2.setOpaque(true);

        jMenu1.setText("Hệ thống");

        mni_dangNhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mni_dangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Key.png"))); // NOI18N
        mni_dangNhap.setText("Đăng nhập");
        mni_dangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_dangNhapActionPerformed(evt);
            }
        });
        jMenu1.add(mni_dangNhap);

        mni_dangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mni_dangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Log out.png"))); // NOI18N
        mni_dangXuat.setText("Đăng xuất");
        mni_dangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_dangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(mni_dangXuat);
        jMenu1.add(jSeparator1);

        mni_doiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Refresh.png"))); // NOI18N
        mni_doiMatKhau.setText("Đổi mật khẩu");
        jMenu1.add(mni_doiMatKhau);
        jMenu1.add(jSeparator2);

        mni_ketThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mni_ketThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Stop.png"))); // NOI18N
        mni_ketThuc.setText("Kết thúc");
        jMenu1.add(mni_ketThuc);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        mni_chuyenDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        mni_chuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Lists.png"))); // NOI18N
        mni_chuyenDe.setText("Chuyên đề");
        jMenu2.add(mni_chuyenDe);

        mni_khoaHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
        mni_khoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Certificate.png"))); // NOI18N
        mni_khoaHoc.setText("Khóa học");
        jMenu2.add(mni_khoaHoc);

        mni_nguoiHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_MASK));
        mni_nguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Conference.png"))); // NOI18N
        mni_nguoiHoc.setText("Người học");
        mni_nguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_nguoiHocActionPerformed(evt);
            }
        });
        jMenu2.add(mni_nguoiHoc);

        mni_hocVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        mni_hocVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/User.png"))); // NOI18N
        mni_hocVien.setText("Học viên");
        jMenu2.add(mni_hocVien);
        jMenu2.add(jSeparator6);

        mni_nhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_MASK));
        mni_nhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/User group.png"))); // NOI18N
        mni_nhanVien.setText("Nhân viên");
        mni_nhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_nhanVienActionPerformed(evt);
            }
        });
        jMenu2.add(mni_nhanVien);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Thống kê");

        mni_thongKeNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Clien list.png"))); // NOI18N
        mni_thongKeNguoiHoc.setText("Người học từng năm");
        jMenu3.add(mni_thongKeNguoiHoc);
        jMenu3.add(jSeparator3);

        mni_thongKeBangDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Card file.png"))); // NOI18N
        mni_thongKeBangDiem.setText("Bảng điểm khóa...");
        jMenu3.add(mni_thongKeBangDiem);

        mni_thongKeKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Bar chart.png"))); // NOI18N
        mni_thongKeKhoaHoc.setText("Điểm từng khóa học");
        jMenu3.add(mni_thongKeKhoaHoc);
        jMenu3.add(jSeparator4);

        mni_thongKeDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Dollar.png"))); // NOI18N
        mni_thongKeDoanhThu.setText("Doanh thu từng chuyên đề...");
        jMenu3.add(mni_thongKeDoanhThu);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Trợ giúp");

        mni_huongDan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mni_huongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Globe.png"))); // NOI18N
        mni_huongDan.setText("Hướng dẫn sử dụng");
        jMenu5.add(mni_huongDan);
        jMenu5.add(jSeparator5);

        mni_gioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Brick house.png"))); // NOI18N
        mni_gioiThieu.setText("Giới thiệu sản phẩm");
        jMenu5.add(mni_gioiThieu);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dangXuatActionPerformed

    private void btn_nguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nguoiHocActionPerformed
        new QuanLyNguoiHocJFrame().setVisible(true);
    }//GEN-LAST:event_btn_nguoiHocActionPerformed

    private void mni_dangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_dangNhapActionPerformed
        new DangNhapJFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mni_dangNhapActionPerformed

    private void mni_nguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_nguoiHocActionPerformed
        new QuanLyNguoiHocJFrame().setVisible(true);
    }//GEN-LAST:event_mni_nguoiHocActionPerformed

    private void mni_dangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_dangXuatActionPerformed
        ShareHelper.logoff();
        new DangNhapJFrame().setVisible(true);
    }//GEN-LAST:event_mni_dangXuatActionPerformed

    private void mni_nhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_nhanVienActionPerformed
        new QuanLyNhanVienJFrame().setVisible(true);
    }//GEN-LAST:event_mni_nhanVienActionPerformed

    private void btn_khoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_khoaHocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_khoaHocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EduSysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EduSysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EduSysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EduSysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EduSysJFrame().setVisible(false);
                new ChaoJDialog().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chuyenDe;
    private javax.swing.JButton btn_dangXuat;
    private javax.swing.JButton btn_hocVien;
    private javax.swing.JButton btn_huongDan;
    private javax.swing.JButton btn_ketThuc;
    private javax.swing.JButton btn_khoaHoc;
    private javax.swing.JButton btn_nguoiHoc;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbl_dongHo;
    private javax.swing.JLabel lbl_trangThai;
    private javax.swing.JMenuItem mni_chuyenDe;
    private javax.swing.JMenuItem mni_dangNhap;
    private javax.swing.JMenuItem mni_dangXuat;
    private javax.swing.JMenuItem mni_doiMatKhau;
    private javax.swing.JMenuItem mni_gioiThieu;
    private javax.swing.JMenuItem mni_hocVien;
    private javax.swing.JMenuItem mni_huongDan;
    private javax.swing.JMenuItem mni_ketThuc;
    private javax.swing.JMenuItem mni_khoaHoc;
    private javax.swing.JMenuItem mni_nguoiHoc;
    private javax.swing.JMenuItem mni_nhanVien;
    private javax.swing.JMenuItem mni_thongKeBangDiem;
    private javax.swing.JMenuItem mni_thongKeDoanhThu;
    private javax.swing.JMenuItem mni_thongKeKhoaHoc;
    private javax.swing.JMenuItem mni_thongKeNguoiHoc;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setLocationRelativeTo(null);
        this.setIconImage(XImage.getAppIcon());
        setTitle("HỆ THỐNG QUẢN LÝ ĐÀO TẠO");
        Thread th = new Thread(this);
        th.start();
    }

    @Override
    public void run() {
        while (true) {
            try {
                Date now = new Date();
                SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss aa");
                String time = formater.format(now);
                lbl_dongHo.setText(time);
            } catch (Exception e) {
            }
        }
    }
}
