/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.DAO.NhanVienDAO;
import com.edusys.Interface.IService;
import com.edusys.helper.DialogHelper;
import com.edusys.helper.ShareHelper;
import com.edusys.model.NhanVien;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class QuanLyNhanVienJInternalFrame extends javax.swing.JInternalFrame implements IService {

    /**
     * Creates new form QuanLyNhanVienJInternalFrame
     */
    DefaultTableModel tblModel = new DefaultTableModel(new String[]{"MÃ NV", "HỌ VÀ TÊN", "VAI TRÒ"}, 0);
    NhanVienDAO nhanVienDAO = new NhanVienDAO();
    List<NhanVien> lst_nhanVien = new ArrayList<>();
    int rowIndex = 0;
    int pageNumber = 1;
    int rowsOfPage = 20;
    int totalPage = (int) Math.ceil((double) nhanVienDAO.getTotalRow() / rowsOfPage);

    public QuanLyNhanVienJInternalFrame() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_manv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_hoTen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rdo_truongPhong = new javax.swing.JRadioButton();
        rdo_nhanVien = new javax.swing.JRadioButton();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_moi = new javax.swing.JButton();
        btn_last = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        btn_prev = new javax.swing.JButton();
        btn_first = new javax.swing.JButton();
        txt_matKhau = new javax.swing.JPasswordField();
        txt_xacNhanMatKhau = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_danhSachNhanVien = new javax.swing.JTable();
        btn_firstPage = new javax.swing.JButton();
        btn_prevPage = new javax.swing.JButton();
        btn_nextPage = new javax.swing.JButton();
        btn_lastPage = new javax.swing.JButton();
        txt_soTrang = new javax.swing.JTextField();
        lbl_tongSoTrang = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN QUẢN TRỊ");

        jLabel2.setText("Mã nhân viên");

        jLabel3.setText("Mật khẩu");

        jLabel4.setText("Xác nhận mật khẩu");

        jLabel5.setText("Họ và tên");

        jLabel6.setText("Vai trò");

        rdo_truongPhong.setText("Trưởng phòng");

        rdo_nhanVien.setSelected(true);
        rdo_nhanVien.setText("Nhân viên");

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_moi.setText("Mới");
        btn_moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moiActionPerformed(evt);
            }
        });

        btn_last.setText(">|");
        btn_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lastActionPerformed(evt);
            }
        });

        btn_next.setText(">>");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        btn_prev.setText("<<");
        btn_prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prevActionPerformed(evt);
            }
        });

        btn_first.setText("|<");
        btn_first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_firstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_manv)
                    .addComponent(txt_hoTen)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_them)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_sua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_xoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_moi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(btn_first)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_prev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_next)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_last))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rdo_truongPhong)
                                .addGap(18, 18, 18)
                                .addComponent(rdo_nhanVien)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_matKhau)
                    .addComponent(txt_xacNhanMatKhau))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_manv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_xacNhanMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_truongPhong)
                    .addComponent(rdo_nhanVien))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_sua)
                    .addComponent(btn_xoa)
                    .addComponent(btn_moi)
                    .addComponent(btn_last)
                    .addComponent(btn_next)
                    .addComponent(btn_prev)
                    .addComponent(btn_first))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("CẬP NHẬT", jPanel2);

        jPanel3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel3ComponentShown(evt);
            }
        });

        tbl_danhSachNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_danhSachNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_danhSachNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl_danhSachNhanVienMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_danhSachNhanVien);

        btn_firstPage.setText("|<");
        btn_firstPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_firstPageActionPerformed(evt);
            }
        });

        btn_prevPage.setText("<<");
        btn_prevPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prevPageActionPerformed(evt);
            }
        });

        btn_nextPage.setText(">>");
        btn_nextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextPageActionPerformed(evt);
            }
        });

        btn_lastPage.setText(">|");
        btn_lastPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lastPageActionPerformed(evt);
            }
        });

        txt_soTrang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_soTrangKeyReleased(evt);
            }
        });

        lbl_tongSoTrang.setText("/");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btn_firstPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_prevPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_soTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_tongSoTrang)
                        .addGap(18, 18, 18)
                        .addComponent(btn_nextPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_lastPage)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_firstPage)
                    .addComponent(btn_prevPage)
                    .addComponent(btn_nextPage)
                    .addComponent(btn_lastPage)
                    .addComponent(txt_soTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tongSoTrang))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tabs.addTab("DANH SÁCH", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabs)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tabs)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        insert();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        update();
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        delete();
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_moiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moiActionPerformed
        clear();
    }//GEN-LAST:event_btn_moiActionPerformed

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        rowIndex = tbl_danhSachNhanVien.getRowCount() - 1;
        setModel(lst_nhanVien.get(rowIndex));
    }//GEN-LAST:event_btn_lastActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        rowIndex++;
        setModel(lst_nhanVien.get(rowIndex));
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prevActionPerformed
        rowIndex--;
        setModel(lst_nhanVien.get(rowIndex));
    }//GEN-LAST:event_btn_prevActionPerformed

    private void btn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        rowIndex = 0;
        setModel(lst_nhanVien.get(rowIndex));
    }//GEN-LAST:event_btn_firstActionPerformed

    private void tbl_danhSachNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_danhSachNhanVienMouseClicked
        {
            rowIndex = tbl_danhSachNhanVien.getSelectedRow();
            setModel(lst_nhanVien.get(rowIndex));
            tabs.setSelectedIndex(0);
            setBtnEnabled(true);
        }
    }//GEN-LAST:event_tbl_danhSachNhanVienMouseClicked

    private void tbl_danhSachNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_danhSachNhanVienMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_danhSachNhanVienMouseEntered

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        ShareHelper.OPENING = false;
    }//GEN-LAST:event_formInternalFrameClosing

    private void btn_firstPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstPageActionPerformed
        changePage("first");
    }//GEN-LAST:event_btn_firstPageActionPerformed

    private void btn_prevPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prevPageActionPerformed
        changePage("prev");
    }//GEN-LAST:event_btn_prevPageActionPerformed

    private void btn_nextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextPageActionPerformed
        changePage("next");
    }//GEN-LAST:event_btn_nextPageActionPerformed

    private void btn_lastPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastPageActionPerformed
        changePage("last");
    }//GEN-LAST:event_btn_lastPageActionPerformed

    private void txt_soTrangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_soTrangKeyReleased

    }//GEN-LAST:event_txt_soTrangKeyReleased

    private void jPanel3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel3ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3ComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_firstPage;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_lastPage;
    private javax.swing.JButton btn_moi;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_nextPage;
    private javax.swing.JButton btn_prev;
    private javax.swing.JButton btn_prevPage;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_tongSoTrang;
    private javax.swing.JRadioButton rdo_nhanVien;
    private javax.swing.JRadioButton rdo_truongPhong;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tbl_danhSachNhanVien;
    private javax.swing.JTextField txt_hoTen;
    private javax.swing.JTextField txt_manv;
    private javax.swing.JPasswordField txt_matKhau;
    private javax.swing.JTextField txt_soTrang;
    private javax.swing.JPasswordField txt_xacNhanMatKhau;
    // End of variables declaration//GEN-END:variables

    private void init() {
//        setLocationRelativeTo(null);
//        setIconImage(XImage.getAppIcon());
        BasicInternalFrameUI basicInternalFrameUI = ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI());
        for (MouseListener listener : basicInternalFrameUI.getNorthPane().getMouseListeners()) {
            basicInternalFrameUI.getNorthPane().removeMouseListener(listener);
        }
        setTitle("QUẢN LÝ NHÂN VIÊN");
        setBtnEnabled(false);
        tbl_danhSachNhanVien.setModel(tblModel);
        loadTable();
    }

    @Override
    public void loadTable() {
        try {
//            lst_nhanVien = nhanVienDAO.selectAll();
            tblModel.setRowCount(0);
            totalPage = (int) Math.ceil((double) nhanVienDAO.getTotalRow() / rowsOfPage);
            if (pageNumber > totalPage) {
                pageNumber = 1;
            }
            lst_nhanVien = nhanVienDAO.selectByPage(pageNumber, rowsOfPage);
            for (NhanVien x : lst_nhanVien) {
                {
                    tblModel.addRow(new Object[]{x.getMaNV(), x.getHoTen(), x.isVaiTro() ? "Trưởng phòng" : "Nhân viên"});
                }
            }
            btnStatus();
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    @Override
    public void insert() {
        if (getModel() != null) {
            try {
                nhanVienDAO.insert(getModel());
                loadTable();
                clear();
                DialogHelper.alert(this, "Thêm mới thành công!");
            } catch (Exception e) {
                DialogHelper.alert(this, "Thêm mới thất bại!");
            }
        }
    }

    @Override
    public void delete() {
        String manv = txt_manv.getText();
        if (!manv.equals(ShareHelper.USER.getMaNV())) {
            if (rowIndex >= 0) {
                if (DialogHelper.confirm(this, "Bạn thực sự muốn xóa nhân viên này?")) {
                    try {
                        nhanVienDAO.delete(manv);
                        loadTable();
                        clear();
                        DialogHelper.alert(this, "Xóa thành công!");
                    } catch (Exception e) {
                        DialogHelper.alert(this, "Xóa thất bại!");
                    }
                }
            }
        } else {
            DialogHelper.alert(this, "Bạn không thể xóa bản thân!");
        }

    }

    @Override
    public void update() {
        if (getModel() != null) {
            try {
                nhanVienDAO.update(getModel());
                loadTable();
                DialogHelper.alert(this, "Cập nhật thành công!");
            } catch (Exception e) {
                DialogHelper.alert(this, "Cập nhật thất bại!");
            }
        }
    }

    @Override
    public void clear() {
        setModel(new NhanVien());
        setBtnEnabled(false);
    }

    public void setModel(NhanVien model) {
        txt_manv.setText(model.getMaNV());
        txt_hoTen.setText(model.getHoTen());
        txt_matKhau.setText(model.getMatKhau());
        txt_xacNhanMatKhau.setText(model.getMatKhau());
        rdo_truongPhong.setSelected(model.isVaiTro());
        rdo_nhanVien.setSelected(!model.isVaiTro());
        setBtnEnabled(true);
        tbl_danhSachNhanVien.setRowSelectionInterval(rowIndex, rowIndex);
    }

    NhanVien getModel() {
        if (checkField().length() > 0) {
            DialogHelper.alert(this, checkField().toString());
            return null;
        }
        return new NhanVien(txt_manv.getText(), new String(txt_matKhau.getPassword()), txt_hoTen.getText(), rdo_truongPhong.isSelected());
    }

    @Override
    public StringBuilder checkField() {
        StringBuilder sb = new StringBuilder();
        String manv = txt_manv.getText();
        String hoTen = txt_hoTen.getText();
        String matKhau = new String(txt_matKhau.getPassword());
        String xacNhanMK = new String(txt_xacNhanMatKhau.getPassword());
        if (manv.isBlank()) {
            sb.append("Không được để trống mã nhân viên\n");
        }
        if (hoTen.isBlank()) {
            sb.append("Không được để trống họ tên\n");
        }
        if (matKhau.isBlank()) {
            sb.append("Không được để trống mật khẩu\n");
        }
//        else if (matKhau.trim().length() < 8){
//            sb.append("Mật khẩu dài tối thiểu 8 ký tự");
//        }
        if (!xacNhanMK.equals(matKhau)) {
            sb.append("Xác nhận mật khẩu không đúng!\n");
        }
        return sb;
    }

    @Override
    public void setBtnEnabled(boolean maTonTai) {
        txt_manv.setEnabled(!maTonTai);
        btn_them.setEnabled(!maTonTai);
        btn_sua.setEnabled(maTonTai);
        btn_xoa.setEnabled(maTonTai);

        boolean first = rowIndex > 0;
        boolean last = rowIndex < tbl_danhSachNhanVien.getRowCount() - 1;
        btn_first.setEnabled(first && maTonTai);
        btn_last.setEnabled(last && maTonTai);
        btn_prev.setEnabled(first && maTonTai);
        btn_next.setEnabled(last && maTonTai);
    }

    void changePage(String button) {
        switch (button) {
            case "first": {
                pageNumber = 1;
                break;
            }
            case "prev": {
                pageNumber--;
                break;
            }
            case "next": {
                pageNumber++;
                break;
            }
            case "last": {
                pageNumber = totalPage;
                break;
            }
        }
        loadTable();
    }

    void btnStatus() {
        txt_soTrang.setText(pageNumber + "");
        lbl_tongSoTrang.setText("/" + totalPage + "");
        btn_firstPage.setEnabled(pageNumber > 1);
        btn_prevPage.setEnabled(pageNumber > 1);
        btn_lastPage.setEnabled(pageNumber < totalPage);
        btn_nextPage.setEnabled(pageNumber < totalPage);
    }
}
