/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

/**
 *
 * @author Dell
 */

import com.edusys.Interface.IService;
import com.edusys.DAO.ChuyenDeDAO;
import com.edusys.DAO.HocVienDAO;
import com.edusys.DAO.KhoaHocDAO;
import com.edusys.DAO.NguoiHocDAO;
import com.edusys.helper.DateHelper;
import com.edusys.helper.DialogHelper;
import com.edusys.helper.ShareHelper;
import com.edusys.helper.Utils;
import com.edusys.model.ChuyenDe;
import com.edusys.model.HocVien;
import com.edusys.model.KhoaHoc;
import com.edusys.model.NguoiHoc;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

public class QuanLyHocVienJInternalFrame extends javax.swing.JInternalFrame implements IService {

    /**
     * Creates new form QuanLyHocVienJInternalFrame
     */
    
    DefaultTableModel tblModel_hocVien = new DefaultTableModel(new String[]{"TT", "MÃ HV", "MÃ NH", "HỌ TÊN", "ĐIỂM"}, 0);
    DefaultTableModel tblModel_nguoiHoc = new DefaultTableModel(new String[]{"MÃ NH", "HỌ TÊN", "GIỚI TÍNH", "NGÀY SINH", "ĐIỆN THOẠI", "EMAIL"}, 0);
    List<KhoaHoc> lst_khoaHoc = new ArrayList<>();
    List<ChuyenDe> lst_chuyenDe = new ArrayList<>();
    List<NguoiHoc> lst_nguoiHoc = new ArrayList<>();
    List<HocVien> lst_hocVien = new ArrayList<>();
    KhoaHocDAO khoaHocDAO = new KhoaHocDAO();
    ChuyenDeDAO chuyenDeDAO = new ChuyenDeDAO();
    NguoiHocDAO nguoiHocDAO = new NguoiHocDAO();
    HocVienDAO hocVienDAO = new HocVienDAO();
    String keyword = "";
    int rowIndex_hocVien = 0;
    int maKH = -1;
    int pageNumber = 1;
    int rowsOfPage = 10;
    int totalPage = (int) Math.ceil((double) nguoiHocDAO.getTotalRow(keyword) / rowsOfPage);
    
    public QuanLyHocVienJInternalFrame() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbo_chuyenDe = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbo_khoaHoc = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_danhSachHocVien = new javax.swing.JTable();
        btn_capNhatDiem = new javax.swing.JButton();
        btn_xoaHocVien = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txt_timNguoiHoc = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_danhSachNguoiHoc = new javax.swing.JTable();
        btn_themHocVien = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_firstPage = new javax.swing.JButton();
        btn_prevPage = new javax.swing.JButton();
        btn_nextPage = new javax.swing.JButton();
        btn_lastPage = new javax.swing.JButton();
        txt_soTrang = new javax.swing.JTextField();
        lbl_tongSoTrang = new javax.swing.JLabel();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CHUYÊN ĐỀ");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        cbo_chuyenDe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbo_chuyenDe, 0, 229, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbo_chuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("KHÓA HỌC");

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        cbo_khoaHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbo_khoaHoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbo_khoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbl_danhSachHocVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_danhSachHocVien);

        btn_capNhatDiem.setText("Cập nhật điểm");
        btn_capNhatDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capNhatDiemActionPerformed(evt);
            }
        });

        btn_xoaHocVien.setText("Xóa khỏi khóa học");
        btn_xoaHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaHocVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_xoaHocVien)
                        .addGap(18, 18, 18)
                        .addComponent(btn_capNhatDiem)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_capNhatDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_xoaHocVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("HỌC VIÊN", jPanel3);

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txt_timNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timNguoiHocActionPerformed(evt);
            }
        });
        txt_timNguoiHoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_timNguoiHocKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_timNguoiHoc)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_timNguoiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_danhSachNguoiHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_danhSachNguoiHoc);

        btn_themHocVien.setText("Thêm vào khóa học");
        btn_themHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themHocVienActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Tìm kiếm theo tên");

        btn_firstPage.setText("|<");
        btn_firstPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_firstPageActionPerformed(evt);
            }
        });

        btn_prevPage.setText("<<");
        btn_prevPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prevPageActionPerformed(evt);
            }
        });

        btn_nextPage.setText(">>");
        btn_nextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextPageActionPerformed(evt);
            }
        });

        btn_lastPage.setText(">|");
        btn_lastPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lastPageActionPerformed(evt);
            }
        });

        txt_soTrang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_soTrangKeyReleased(evt);
            }
        });

        lbl_tongSoTrang.setText("/");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btn_firstPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_prevPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_soTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_tongSoTrang)
                        .addGap(18, 18, 18)
                        .addComponent(btn_nextPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_lastPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_themHocVien))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_themHocVien)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_firstPage)
                        .addComponent(btn_prevPage)
                        .addComponent(btn_nextPage)
                        .addComponent(btn_lastPage)
                        .addComponent(txt_soTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_tongSoTrang)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("NGƯỜI HỌC", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_capNhatDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capNhatDiemActionPerformed
        update();
    }//GEN-LAST:event_btn_capNhatDiemActionPerformed

    private void btn_xoaHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaHocVienActionPerformed
        delete();
    }//GEN-LAST:event_btn_xoaHocVienActionPerformed

    private void txt_timNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timNguoiHocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timNguoiHocActionPerformed

    private void txt_timNguoiHocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_timNguoiHocKeyReleased
        keyword = txt_timNguoiHoc.getText();
        loadTable_nguoiHoc();
    }//GEN-LAST:event_txt_timNguoiHocKeyReleased

    private void btn_themHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themHocVienActionPerformed
        insert();
    }//GEN-LAST:event_btn_themHocVienActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        ShareHelper.OPENING = false;
    }//GEN-LAST:event_formInternalFrameClosing

    private void btn_firstPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstPageActionPerformed
        changePage("first");
    }//GEN-LAST:event_btn_firstPageActionPerformed

    private void btn_prevPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prevPageActionPerformed
        changePage("prev");
    }//GEN-LAST:event_btn_prevPageActionPerformed

    private void btn_nextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextPageActionPerformed
        changePage("next");
    }//GEN-LAST:event_btn_nextPageActionPerformed

    private void btn_lastPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastPageActionPerformed
        changePage("last");
    }//GEN-LAST:event_btn_lastPageActionPerformed

    private void txt_soTrangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_soTrangKeyReleased

    }//GEN-LAST:event_txt_soTrangKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_capNhatDiem;
    private javax.swing.JButton btn_firstPage;
    private javax.swing.JButton btn_lastPage;
    private javax.swing.JButton btn_nextPage;
    private javax.swing.JButton btn_prevPage;
    private javax.swing.JButton btn_themHocVien;
    private javax.swing.JButton btn_xoaHocVien;
    private javax.swing.JComboBox<String> cbo_chuyenDe;
    private javax.swing.JComboBox<String> cbo_khoaHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_tongSoTrang;
    private javax.swing.JTable tbl_danhSachHocVien;
    private javax.swing.JTable tbl_danhSachNguoiHoc;
    private javax.swing.JTextField txt_soTrang;
    private javax.swing.JTextField txt_timNguoiHoc;
    // End of variables declaration//GEN-END:variables

    @Override
    public void loadTable() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setBtnEnabled(boolean maTonTai) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public StringBuilder checkField() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void insert() {
        StringBuilder sb = new StringBuilder();
        if (cbo_khoaHoc.getSelectedIndex() == 0 || !cbo_khoaHoc.isValid()) {
            DialogHelper.alert(this, "Cần chọn khóa học trước!");
            return;
        }
        int[] rowIndex_nguoiHoc = tbl_danhSachNguoiHoc.getSelectedRows();
        for (int i : rowIndex_nguoiHoc) {
            boolean hocVienTonTai = false;
            String maNH = lst_nguoiHoc.get(i).getMaNH();
            for (HocVien x : lst_hocVien) {
                if (maNH.equals(x.getMaNH())) {
                    sb.append(maNH + "đã có trong khóa học!\n");
                    hocVienTonTai = true;
                }
            }
            if (!hocVienTonTai) {
                HocVien model = new HocVien();
                model.setMaNH(maNH);
                model.setDiem(-1);
                model.setMaKH(maKH);
                hocVienDAO.insert(model);
                sb.append("Thêm thành công học viên " + maNH + "\n");
            }
        }
        DialogHelper.alert(this, sb.toString());
        loadTable_hocVien();
    }

    @Override
    public void update() {
        double diem;
        for (int i = 0; i < lst_hocVien.size(); i++) {
            try {
                diem = Double.parseDouble(tbl_danhSachHocVien.getValueAt(i, 4).toString());
                if (lst_hocVien.get(i).getDiem() != diem) {
                    lst_hocVien.get(i).setDiem(diem);
                    hocVienDAO.update(lst_hocVien.get(i));
                }
            } catch (Exception e) {                
            }
        }
    }

    @Override
    public void delete() {
        int[] rowIndex_hocVien = tbl_danhSachHocVien.getSelectedRows();
        List<Integer> lst_maHV = new ArrayList<>();
        for (int i : rowIndex_hocVien) {
            lst_maHV.add(lst_hocVien.get(i).getMaHV());
        }
        for (Integer maHV : lst_maHV) {
            hocVienDAO.delete(maHV);
        }
        loadTable_hocVien();
    }

    @Override
    public void clear() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void loadComboboxChuyenDe() {
        DefaultComboBoxModel cbo_modelChuyenDe = (DefaultComboBoxModel) cbo_chuyenDe.getModel();
        cbo_modelChuyenDe.removeAllElements();
        try {
            lst_chuyenDe = chuyenDeDAO.selectAll();
            for (ChuyenDe x : lst_chuyenDe) {
                cbo_modelChuyenDe.addElement(x.getTenCD());
            }
            loadComboboxKhoaHoc();
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn KhoaHoc!");
        }
    }

    void changeComboboxChuyenDe() {
        cbo_chuyenDe.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                loadComboboxKhoaHoc();
            }
        });
    }

    void changeComboboxKhoaHoc() {
        cbo_khoaHoc.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tblModel_hocVien.setRowCount(0);
                if (cbo_khoaHoc.isValid()) {
                    loadTable_hocVien();
                }
            }
        });
    }

    void loadComboboxKhoaHoc() {
        DefaultComboBoxModel cbo_modelKhoaHoc = (DefaultComboBoxModel) cbo_khoaHoc.getModel();
        cbo_modelKhoaHoc.removeAllElements();
        String maCD = lst_chuyenDe.get(cbo_chuyenDe.getSelectedIndex()).getMaCD();
        try {
            lst_khoaHoc = khoaHocDAO.selectByMaCD(maCD);
            if (lst_khoaHoc.isEmpty() || lst_khoaHoc == null) {
                cbo_modelKhoaHoc.addElement("Chưa có khóa học nào");
                return;
            }
            cbo_modelKhoaHoc.addElement("Mời chọn khóa học:");
            for (KhoaHoc x : lst_khoaHoc) {
                cbo_modelKhoaHoc.addElement(new Utils().getTenKH(x.getMaKH()));
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn HocVien!");
        }
//        loadTable_hocVien();
    }

    void loadTable_hocVien() {
        tblModel_hocVien.setRowCount(0);
        try {
            maKH = lst_khoaHoc.get(cbo_khoaHoc.getSelectedIndex() - 1).getMaKH();
            System.out.println(maKH);
            lst_hocVien = hocVienDAO.selectByCourse(maKH);
            for (HocVien x : lst_hocVien) {
                tblModel_hocVien.addRow(new Object[]{lst_hocVien.indexOf(x) + 1, x.getMaHV(), x.getMaNH(),
                    nguoiHocDAO.selectById(x.getMaNH()).getHoTen(), x.getDiem()});
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu loadTable_hocVien!");
        }
    }

     void loadTable_nguoiHoc() {
        tblModel_nguoiHoc.setRowCount(0);
        try {
            totalPage = (int) Math.ceil((double) nguoiHocDAO.getTotalRow(keyword) / rowsOfPage);
            if(pageNumber > totalPage){
                pageNumber = 1;
            }
            lst_nguoiHoc = nguoiHocDAO.selectByKeyword(keyword, pageNumber, 10);
            for (NguoiHoc x : lst_nguoiHoc) {
                tblModel_nguoiHoc.addRow(new Object[]{x.getMaNH(), x.getHoTen(), x.isGioiTinh() ? "Nam" : "Nữ",
                    DateHelper.toString(x.getNgaySinh()), x.getDienThoai(), x.getEmail()});
            }
            btnStatus();
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu loadTable_nguoiHoc!");
        }
    }
    
    void changePage(String button) {
        switch (button) {
            case "first": {
                pageNumber = 1;
                break;
            }
            case "prev": {
                pageNumber--;
                break;
            }
            case "next": {
                pageNumber++;
                break;
            }
            case "last": {
                pageNumber = totalPage;
                break;
            }
        }
        loadTable_nguoiHoc();
        
    }
    
    void btnStatus() {
        txt_soTrang.setText(pageNumber + "");
        lbl_tongSoTrang.setText("/" + totalPage + "");
        btn_firstPage.setEnabled(pageNumber > 1);
        btn_prevPage.setEnabled(pageNumber > 1);
        btn_lastPage.setEnabled(pageNumber < totalPage);
        btn_nextPage.setEnabled(pageNumber < totalPage);
    }

    private void init() {
//        this.setLocationRelativeTo(null);
//        this.setIconImage(ShareHelper.APP_ICON);
        setTitle("QUẢN LÝ HỌC VIÊN");
        tbl_danhSachHocVien.setModel(tblModel_hocVien);
        tbl_danhSachNguoiHoc.setModel(tblModel_nguoiHoc);
        loadTable_nguoiHoc();
        loadComboboxChuyenDe();
        changeComboboxChuyenDe();
        changeComboboxKhoaHoc();
        tbl_danhSachNguoiHoc.setRowSelectionAllowed(true);
        tbl_danhSachNguoiHoc.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        
        txt_soTrang.addActionListener(new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                try {
                    pageNumber = Integer.parseInt(txt_soTrang.getText());
                    pageNumber = pageNumber > totalPage ? totalPage : pageNumber;
                    loadTable_nguoiHoc();
                } catch (NumberFormatException e) {
                    System.out.println("loi");
                }
            }            
        });
    }

}
